
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASHI
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        j1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        j3 = new javax.swing.JCheckBox();
        j2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 96, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 242, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 239, 105, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 99, 20));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 375, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        j3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("View Password");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        jPanel1.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 110, -1));

        j2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 250, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASHI\\Desktop\\OIP (2)-modified.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user=j1.getText();
        String pass=j2.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Ashi@8208");
             
            Statement st=con.createStatement();
            Statement st2=con.createStatement();
            Statement st3=con.createStatement();
            Statement st4=con.createStatement();
             Statement st5=con.createStatement();
             Statement st6=con.createStatement();
             Statement st7=con.createStatement();
             Statement st8=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student where student.Branch='CSE' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
             if(rs.next())
            {
                 setVisible(false);
                new Studentportal(user,pass).setVisible(true);
            }
             ResultSet rs2=st2.executeQuery("select * from student where student.Course='B.A' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs2.next()){
                         setVisible(false);
                new Studentportal6(user,pass).setVisible(true);
                     }
            ResultSet rs3=st3.executeQuery("select * from student where student.Branch='EEE' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs3.next()){
                         setVisible(false);
                new Studentportal1(user,pass).setVisible(true);
                     }
                     ResultSet rs4=st4.executeQuery("select * from student where student.Branch='ECE' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs4.next()){
                         setVisible(false);
                new Studentportal2(user,pass).setVisible(true);
                     }
            ResultSet rs5=st5.executeQuery("select * from student where student.Branch='CE' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs5.next()){
                         setVisible(false);
                new Studentportal3(user,pass).setVisible(true);
                     }
            ResultSet rs6=st6.executeQuery("select * from student where student.Branch='HR' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs6.next()){
                         setVisible(false);
                new Studentportal4(user,pass).setVisible(true);
                     }
            ResultSet rs7=st7.executeQuery("select * from student where student.Branch='Finanace' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs7.next()){
                         setVisible(false);
                new Studentportal5(user,pass).setVisible(true);
                     }
            ResultSet rs8=st8.executeQuery("select * from student where student.Course='M.A' and student.Roll_No='"+user+"' and student.Name='"+pass+"'");
                     if(rs8.next()){
                         setVisible(false);
                new Studentportal6(user,pass).setVisible(true);
                     }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        if(j3.isSelected())
        {
            j2.setEchoChar((char)0);
        }else
        {
            j2.setEchoChar('*');
        }
    }//GEN-LAST:event_j3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JPasswordField j2;
    private javax.swing.JCheckBox j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
